option(ENABLE_TESTS "Build unit tests" OFF)

if (BTR_X86 GREATER 0)
  if (ENABLE_TESTS)
    enable_testing()
    add_subdirectory(${PROJECT_SOURCE_DIR}/test)
  endif()
else ()
  message(STATUS "Project ${PROJECT_NAME} doesn't support unit testing on ${BOARD_FAMILY}")
endif()
